sudo: false
language: java
jdk:
  - oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_twigPluginVersion=${TWIG_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_toolboxPluginVersion=${TOOLBOX_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_annotationPluginVersion=${ANNOTATION_PLUGIN_VERSION}"

env:
  - PHPSTORM_ENV="skip incomplete" IDEA_VERSION="IU-183.2153.8" PHP_PLUGIN_VERSION="183.2153.44" TWIG_PLUGIN_VERSION="183.2153.44" TOOLBOX_PLUGIN_VERSION="0.4.6" ANNOTATION_PLUGIN_VERSION="5.3"
  - PHPSTORM_ENV="skip incomplete" IDEA_VERSION="IU-2018.2.5" PHP_PLUGIN_VERSION="182.4892.16" TWIG_PLUGIN_VERSION="182.3458.35" TOOLBOX_PLUGIN_VERSION="0.4.6" ANNOTATION_PLUGIN_VERSION="5.3"
  - PHPSTORM_ENV="skip incomplete" IDEA_VERSION="IU-2018.2" PHP_PLUGIN_VERSION="182.3684.42" TWIG_PLUGIN_VERSION="182.3458.35" TOOLBOX_PLUGIN_VERSION="0.4.6" ANNOTATION_PLUGIN_VERSION="5.3"
  - PHPSTORM_ENV="skip incomplete" IDEA_VERSION="IU-2018.3.6" PHP_PLUGIN_VERSION="183.5429.47" TWIG_PLUGIN_VERSION="183.3795.24" TOOLBOX_PLUGIN_VERSION="0.4.6" ANNOTATION_PLUGIN_VERSION="5.3"

script:
- "./gradlew check verifyPlugin buildPlugin"
